# helm upgrade loki loki/loki-stack --install --namespace monitoring --values ./loki.yaml
loki:
  replicas: 2
  persistence:
    enabled: true
    storageClassName: azure-premium
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - loki
        topologyKey: "kubernetes.io/hostname"