# repo: helm repo add stable https://kubernetes-charts.storage.googleapis.com
# helm2: helm install --name prometheus stable/prometheus --version 9.3.1 --namespace monitoring --values ./prometheus.yaml
# helm3: helm install prometheus stable/prometheus --version 9.3.1 --namespace monitoring --values ./prometheus.yaml
podSecurityPolicy:
  enabled: true

server:
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 200m
  statefulSet:
    enabled: false
  persistentVolume:
    enabled: true
    storageClass: azure-file-standard-lrs
  retention: "15d"
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - prometheus
            - key: component
              operator: In
              values:
              - server
          topologyKey: kubernetes.io/hostname
        weight: 100

nodeExporter:
  resources:
    requests: 
      cpu: 10m
      memory: 50Mi
    limits:
      cpu: 200m
      memory: 100Mi

kubeStateMetrics:
  enabled: true

alertmanager:
  enabled: false

pushgateway:
  enabled: false