# helm upgrade prometheus stable/prometheus --install --namespace monitoring --values ./prometheus.yaml
server:
  replicaCount: 2
  statefulSet:
    enabled: true
  persistentVolume:
    enabled: true
    storageClass: azure-premium
alertmanager:
  enabled: false
pushgateway:
  enabled: false