# helm upgrade prometheus stable/prometheus --version 9.1.2 --install --namespace monitoring --values ./prometheus.yaml
server:
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 200m
  statefulSet:
    enabled: false
  persistentVolume:
    enabled: true
    storageClass: azure-premium
  retention: "15d"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - prometheus
        topologyKey: "kubernetes.io/hostname"

nodeExporter:
  resources:
    requests: 
      cpu: 10m
      memory: 50Mi
    limits:
      cpu: 200m
      memory: 100Mi

kubeStateMetrics:
  enabled: true

alertmanager:
  enabled: false

pushgateway:
  enabled: false