apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: this-cluster-local
spec:
  secretName: this-cluster-local
  dnsNames:
  - www.this-cluster.local
  - www2.this-cluster.local
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - www.this-cluster.local
      - www2.this-cluster.local
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer